services:
  - type: web
    name: pokemon
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm ci
    startCommand: node index.js
    envVars:
      - key: PGDATABASE
        fromDatabase:
          name: pokemondb
          property: database
      - key: PGUSER
        fromDatabase:
          name: pokemondb
          property: user
      - key: PGPASSWORD
        fromDatabase:
          name: pokemondb
          property: password
      - key: PGHOST
        fromDatabase:
          name: pokemondb
          property: host
      - key: PGPORT
        fromDatabase:
          name: pokemondb
          property: port

databases:
  - name: pokemondb
    plan: free
    region: frankfurt
    databaseName: pokemon
    ipAllowList: []
